spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chouillePlanner
    username: root
    password: 'root'
server:
  port: 8082
