spring:
  application:
    name: chouilleplanner
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://mysql:3306/chouillePlanner
    username: root
    password: '{SQL}#42sqlpass'
=======
    url: jdbc:mysql://localhost:3306/java
    username: ali
    password: 'password'
>>>>>>> aliAuthService
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8100/eureka
