spring:
  application:
    name: chouilleplanner
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/java
    username: ali
    password: 'password'
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka
