spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/java
    username: ali
    password: 'password'
server:
  port: 8082