spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:8889/java
    username: root
    password: 'root'
server:
  port: 8082
